DROP TABLE IF EXISTS AUDIT_LOG;
CREATE TABLE AUDIT_LOG(ID INT PRIMARY KEY,
   CUSTOMER_NUMBER VARCHAR(20),PAY_LOAD VARCHAR(1000));
   
DROP TABLE IF EXISTS ERROR_LOG;
CREATE TABLE ERROR_LOG(ID INT PRIMARY KEY,
   CUSTOMER_NUMBER VARCHAR(20),PAY_LOAD VARCHAR(1000));